### ISSUE TITLE
Members other than island Owner are unable to eat.

### ISSUE THREAD

**Issue by DRodriguezG27** [YorickBM/SkyblockAddon#19]
After some testing it seems there is a missing value that needs to be added to the permission.
Attached a file with the error and exception
[members unable to eat.txt](https://github.com/YorickBM/SkyblockAddon/files/13321096/members.unable.to.eat.txt)

**Comment by YorickBM** [comment]
Hey, this issue has been resolved in 6.1! Thank you for the report.
The download should be available on curseforge now!
