### ISSUE TITLE
How to add friends

### ISSUE THREAD

**Issue by Bennyboy1695** [YorickBM/SkyblockAddon#20]
I'm currently using playing a vault hunters skyblock on a server that is using your mod to do the islands. I want to allow my friends to do stuff on my island but not invite them and saw you have a friends permission group but can't find how to add people to it. So my question is how do you use the friends group in this mod?

**Comment by YorickBM** [comment]
Hey, in the bottom row you have the option to add players to the group. Here you can select whom you wish to be part of this group.

This is done inside of the group permission settings view.

**Comment by Bennyboy1695** [comment]
Thank you, i didnt see that before
